[libraries]
work_lib.files = [
  'hdl/avl_dma/avl_dma.vhd',
  'hdl/avl_version/version_reg.vhd',
  'hdl/avl_version/version_pkg.vhd',
  'hdl/avl_bus_arbiter/avl_bus_arbiter.vhd',
  'hdl/avl_irq/interrupt_control.vhd',
  'hdl/avl_irq/interrupt_pkg.vhd',
  'hdl/avl_gen_register/avl_gen_reg_bank.vhd',
  'hdl/avl_bus_splitter/avl_bus_splitter.vhd',
  'hdl/avl_ram/avl_ram.vhd',
  'hdl/avl_uart/uart_bus_if.vhd',
  'hdl/avl_uart/uart_pkg.vhd',
  'hdl/avl_uart/avl_uart.vhd',
  'hdl/avalon_pkg.vhd',
  'testbench/tb_avl_version.vhd',
  'testbench/tb_avl_bus_splitter.vhd',
  'testbench/tb_avl_irq.vhd',
  'testbench/tb_avl_bus_arbiter.vhd',
  'testbench/tb_avalon_ram.vhd',
  'testbench/tb_avl_reg_bank.vhd',
  'testbench/tb_avl_uart.vhd',
  'external/hdl-base/ram/hdl/ram_tdp.vhd',
  'external/hdl-base/ram/hdl/ram_sdp.vhd',
  'external/hdl-base/fifo/hdl/fifo_sc_single.vhd',
  'external/hdl-base/uart/hdl/uart_tx.vhd',
  'external/hdl-base/uart/hdl/uart_rx.vhd',
  'external/hdl-base/uart/hdl/uart_wrapper_top.vhd',
  'external/hdl-base/arbiter/hdl/arbiter_rr.vhd',
]

vunit_lib.files = [
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/queue_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/dict_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/types.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/data_types_context.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/codec.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/codec-2008p.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/codec_builder.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/vunit_run_context.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/vunit_context.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/core/src/stop_body_2008p.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/core/src/core_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/core/src/stop_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/ansi_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/logger_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/file_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/log_deprecated_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/print_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/print_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/string_ops/src/string_ops.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/check/src/checker_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/check/src/check_deprecated_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/check/src/checker_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/check/src/check.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/check/src/check_api.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/dictionary/src/dictionary.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/run/src/run_deprecated_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/run/src/runner_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/run/src/run.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/run/src/run_api.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/run/src/run_types.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/path/src/path.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/random/src/random_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_messenger.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_api.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_support.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_common.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_string.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_debug_codec_builder.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_context.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_deprecated.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/com/src/com_types.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_stream_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/sync_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/ram_master.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/stream_master_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/stream_master_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/memory_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/uart_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/avalon_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/bus2memory.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_stream_master.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/bus_master_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/stream_slave_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/bus_master_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/avalon_sink.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/memory_pkg-body.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_lite_master_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/memory_utils_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/wishbone_slave.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_stream_monitor.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/avalon_stream_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_stream_slave.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_stream_private_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/uart_slave.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/wishbone_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/std_logic_checker.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/avalon_slave.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_stream_protocol_checker.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/vc_context.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/uart_master.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_statistics_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_slave_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/sync_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_read_slave.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/stream_slave_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/signal_checker_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/wishbone_master.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/avalon_source.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_slave_private_pkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_write_slave.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/avalon_master.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/verification_components/src/axi_lite_master.vhd',
]

osvvm.files = [
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/TextUtilPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/NamePkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/RandomPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/TranscriptPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/RandomBasePkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/MemoryPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/CoveragePkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/VendorCovApiPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/AlertLogPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/TbUtilPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/SortListPkg_int.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/ResolutionPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/MessagePkg.vhd',
  '../../../.local/lib/python3.9/site-packages/vunit/vhdl/osvvm/OsvvmContext.vhd',
]

