[libraries]
work.files = [
  './ram/**/*.vhd',
  './fifo/**/*.vhd',
  './sync/**/*.vhd',
]

osvvm.files = [
  './osvvm/*.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/SortListPkg_int.vhd',
  #'/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_int.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/ResolutionPkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/NamePkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/VendorCovApiPkg.vhd',
  #'/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/MessagePkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/AlertLogPkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/RandomPkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/RandomBasePkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/CoveragePkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/OsvvmContext.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/MemoryPkg.vhd',
  #'/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/ScoreboardGenericPkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/TbUtilPkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/TextUtilPkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/osvvm/TranscriptPkg.vhd',
]

vunit_lib.files = [
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/dictionary/src/dictionary.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/dictionary/test/tb_dictionary.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_types.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_deprecated.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_common.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_debug_codec_builder.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_context.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_support.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_string.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_messenger.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/com/src/com_api.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/path/src/path.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/queue_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/types.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/dict_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/data_types_context.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/codec.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/codec_builder.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/codec-2008p.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/run/src/run_types.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/run/src/run_api.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/run/src/run_deprecated_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/run/src/runner_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/run/src/run.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/print_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/file_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/log_deprecated_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/ansi_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/print_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/logging/src/logger_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/array/src/array_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/vunit_context.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/string_ops/src/string_ops.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_stream_master.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/stream_master_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/avalon_stream_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_write_slave.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/stream_master_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/bus2memory.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/wishbone_master.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/bus_master_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_read_slave.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_stream_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_statistics_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/bus_master_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/vc_context.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/wishbone_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_slave_private_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/avalon_master.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_lite_master_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/sync_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/stream_slave_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/sync_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_stream_slave.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_lite_master.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/uart_slave.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/avalon_sink.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/std_logic_checker.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/uart_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/uart_master.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/ram_master.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_stream_monitor.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/signal_checker_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_stream_protocol_checker.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/avalon_source.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/memory_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/stream_slave_pkg-body.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/memory_utils_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_slave_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/avalon_slave.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/wishbone_slave.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/avalon_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/memory_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/verification_components/src/axi_stream_private_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/core/src/stop_body_2008p.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/core/src/core_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/core/src/stop_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/vunit_run_context.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/random/src/random_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/check/src/checker_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/check/src/check.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/check/src/check_api.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/check/src/check_deprecated_pkg.vhd',
  '/home/phil/.local/lib/python3.8/site-packages/vunit/vhdl/check/src/checker_pkg-body.vhd',
]
