name: CI

on: [push]

jobs:
  vunit-ghdl-sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - uses: docker://ghdl/vunit:gcc
        with:
          args: python3 ./run.py -p 12 -m
